# Reference: https://docs.gitlab.com/ee/ci/yaml/README.html
# Linter: https://gitlab.com/mburolla/serverless-ci-deploy/-/ci/lint

stages: 
 - build

build_stage: 
  stage: build  
  image: node 
  only:
    - stage 
  script:     
    - echo 'hello world'
    - sls deploy
