# Reference: https://docs.gitlab.com/ee/ci/yaml/README.html
# Linter: https://gitlab.com/mburolla/serverless-ci-deploy/-/ci/lint

stages: 
 - build

build_stage: 
  stage: build  
  image: mesosphere/aws-cli
  only:
    - stage 
  before_script:
    - npm config set prefix /usr/local
    - npm install -g serverless
    - npm install
    - pip install awscli
    - aws s3 cp s3://sls-config/stage.json ./config/stage.json
  script:     
    - serverless deploy --verbose
  environment: stage
