# Reference: https://docs.gitlab.com/ee/ci/yaml/README.html

stages: 
 - deploy

deploy: 
  stage: deploy  
  image: node 
  only:
    - stage  # The name of the GitLab branch.
  # script:     
    # - npm run build sls deploy 

