# Reference: https://docs.gitlab.com/ee/ci/yaml/README.html
# Linter: https://gitlab.com/mburolla/serverless-ci-deploy/-/ci/lint

stages: 
 - build

build_stage: 
  stage: build  
  image: node:latest
  only:
    - stage 
  before_script:
    - npm config set prefix /usr/local
    - npm install -g serverless
    - npm install
    - sudo apt-get -y install python3-pip
  script:     
    - serverless deploy --verbose
  environment: stage
