# Reference: https://docs.gitlab.com/ee/ci/yaml/README.html
# Linter: https://gitlab.com/mburolla/serverless-ci-deploy/-/ci/lint

stages: 
 - build

build_stage: 
  stage: build  
  image: node:latest
  only:
    - stage 
  before_script:
    - npm config set prefix /usr/local
    - npm install -g serverless
    - npm install
    - apt-get update
    - apt-get -y install python3-pip
    - pip3 install awscli --upgrade --user
    - export PATH=~/.local/lib/aws/bin/:$PATH
    - source ~/.bash_profile
  script:     
    - aws s3 cp s3://sls-config/stage.json ./config/stage.json
    - serverless deploy --verbose
  environment: stage
