# Reference: https://docs.gitlab.com/ee/ci/yaml/README.html
# Linter: https://gitlab.com/mburolla/serverless-ci-deploy/-/ci/lint

stages: 
 - deploy

deploy_stage: 
  stage: deploy  
  image: node:latest
  only:
    - stage 
  before_script:
    - npm config set prefix /usr/local
    - npm install -g serverless
    - npm install
    - apt-get update
    - apt-get -y install python3-pip
    - pip3 install awscli --upgrade --user
  script:     
    - ~/.local/bin/aws s3 cp s3://sls-config/stage.json ./config/stage.json
    - sls deploy --verbose
  environment: stage

deploy_prod: 
  stage: deploy  
  image: node:latest
  only:
    - master 
  before_script:
    - npm config set prefix /usr/local
    - npm install -g serverless
    - npm install
    - apt-get update
    - apt-get -y install python3-pip
    - pip3 install awscli --upgrade --user
  script:     
    - ~/.local/bin/aws s3 cp s3://sls-config/prod.json ./config/prod.json
    - sls deploy --stage prod --verbose
  environment: prod
